name: Build links (daily, MUVERA-like semantic rerank)

on:
  schedule:
    - cron: "0 3 * * *"   # 03:00 UTC ≈ 06:00 Europe/Kyiv (summer); adjust in winter if needed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run aggregator (daily, categorized, semantic)
        run: python aggregator_links.py
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add links.txt links_by_category.json archive_links.txt seen.json || true
          git commit -m "daily semantic categorized update [skip ci]" || echo "nothing to commit"
          git push
